TechVirtusProvaEverton/TechVirtusProvaEverton/Controllers/EmpresaController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using TechVirtusProvaEverton.DAO;
using TechVirtusProvaEverton.Filtros;
using TechVirtusProvaEverton.Models;

namespace TechVirtusProvaEverton.Controllers
{
    [AutorizacaoFilter]
    public class EmpresaController : Controller
    {
        
        private IList<Empresa> empresas;
        // GET: Empresa
        [Route("empresas",Name ="todasEmpresas")]
        public ActionResult Index()
        {
            empresas = new List<Empresa>();                
            EmpresaDAO dao = new EmpresaDAO();
            empresas = dao.Lista();
            
            return View(empresas);
            
        }
        [Route("formularioEmpresa",Name ="formularioEmp")]    
        
        public ActionResult Formulario()
        {
            ViewBag.Tela = "Cadastro Empresa";
            Empresa empresa = new Empresa();

            TipoServicoDAO daoTipo=new TipoServicoDAO();
            
            return View("Formulario", empresa);
        }
        [Route("atualizaEmpresa/{id}",Name ="AtualizaEmp")]
        public ActionResult Edita(int id)
        {
            EmpresaDAO dao = new EmpresaDAO();
            Empresa empresa = dao.BuscaEmpresaId(id);          
            ViewBag.Tela = "Atualizando Usuário";
            return View("Formulario",empresa);
        }
        [Route("removeEmpresa/{id}",Name ="RemoveEmp")]
        public ActionResult Remove(int id)
        {
            EmpresaDAO dao = new EmpresaDAO();
            Empresa empresa = dao.BuscaEmpresaId(id);
            dao.Remover(empresa);
            return RedirectToRoute("todasEmpresas"); ;
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Adicionar(Empresa empresa)
        {
            
            if(ModelState.IsValid)
            {
                EmpresaDAO dao = new EmpresaDAO();
                if(empresa.Id>0)
                {
                    dao.Atualizar(empresa);
                }
                if(empresa.Id==0)
                {
                    dao.Adicionar(empresa);
                }
                return RedirectToRoute("todasEmpresas");
            }
            else
            {
              
                ModelState.AddModelError("Dados.Invalidos", "Lamentamos a incoviniencia, por favor verifique novamente as informações digitadas algo está invalido, obrigado..");
                return View("Formulario", empresa);
            }
                                    
        }
        [Route("empresas/{id}", Name = "VisualizaEmpresas")]
        public ActionResult Vizualiza(int id)
        {
            EmpresaDAO dao = new EmpresaDAO();
            Empresa empresa = new Empresa();
            empresa = dao.BuscaEmpresaId(id);

            ViewBag.Empresa = empresa;

            return View();
        }
        
    }
    
}

TechVirtusProvaEverton/TechVirtusProvaEverton/Controllers/TipoServicoController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using TechVirtusProvaEverton.DAO;
using TechVirtusProvaEverton.Filtros;
using TechVirtusProvaEverton.Models;

namespace TechVirtusProvaEverton.Controllers
{
    [AutorizacaoFilter]
    public class TipoServicoController : Controller
    {
      
        // GET: TipoServico
       [Route("tiposServicos",Name ="todosServ")]
        public ActionResult Index()
        {
            TipoServicoDAO dao = new TipoServicoDAO();
            IList<TipoServico> tipo=dao.Lista();
            ViewBag.TipoServico = tipo;
            return View();
        }
        [Route("formularioServico",Name ="formularioServ")]
        public ActionResult Formulario()
        {
            ViewBag.Tela = "Cadastro Novo Serviço";
            TipoServico tipo = new TipoServico();
            return View("Formulario",tipo);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Adiciona(TipoServico tipo)
        {
            
            if (ModelState.IsValid)
            {
                TipoServicoDAO dao = new TipoServicoDAO();
                if(tipo.Id>0)
                {
                    dao.Atualizar(tipo);
                                        
                    
                }
                if(tipo.Id==0)
                {
                    dao.Adicionar(tipo);
                    
                }
                return RedirectToRoute("todosServ");
            }
            else
            {

                ModelState.AddModelError("tipoServico.Invalido", "Lamentamos a incoviniencia, por favor verifique novamente as informações digitadas algo está invalido, obrigado..");
                
            }
             tipo = new TipoServico();
            return View("Formulario",tipo);

        }
        [Route("atualizaTipoServico/{id}", Name = "AtualizaTipoServ")]
        public ActionResult Edita(int id)
        {

            TipoServicoDAO dao = new TipoServicoDAO();
            TipoServico tipo = new TipoServico();
            tipo = dao.BuscarPorId(id);
            ViewBag.Tela = "Atualizando Serviço";

            return View("Formulario",tipo);
        }
        [Route("removeTipoServico/{id}", Name = "RemoveTipoServ")]
        public ActionResult Remove(int id)
        {
            TipoServicoDAO dao = new TipoServicoDAO();
            TipoServico tipo=dao.BuscarPorId(id);
            dao.Remover(tipo);

            return RedirectToRoute("todosServ");
        }
        [Route("tiposServicos/{id}", Name = "VisualizaServicos")]
        public ActionResult Vizualiza(int id)
        {
            TipoServicoDAO dao = new TipoServicoDAO();
            TipoServico tipo = new TipoServico();
            tipo = dao.BuscarPorId(id);

            ViewBag.TipoServico = tipo;

            return View();
        }
       
    }
}

TechVirtusProvaEverton/TechVirtusProvaEverton/Views/Shared/_Analista.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Prova TECHVIRTUS</title>
    <link rel="icon" href="~/Content/img/logoAba.png">
    <link rel="stylesheet" type="text/css" href="~/Content/css/Principal.css">
    <link rel="stylesheet" type="text/css" href="~/Content/css/menuAcordion.css">
    <link rel="stylesheet" type="text/css" href="~/Content/css/CabecalhoTabelas.css">
    <link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
    <link rel="stylesheet" type="text/css" href="~/Content/css/formularios.css">
    <link rel="stylesheet" type="text/css" href="~/Content/css/validacoes.css">

    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a href="~/Home/Index" style="text-decoration:none;color:dimgrey;"><img src="~/Content/img/logo.png" /></a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Logout", "Logout", "Usuario")</li>
                    <li>@Html.ActionLink("Início", "Index", "Home")</li>
                    <li>@Html.ActionLink("Sobre", "About", "Home")</li>
                    <li>@Html.ActionLink("Contato", "Contact", "Home")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content contaner">
        <div id="conteudo">
            @RenderBody()
        </div>
        <!--Menu-->
        <div id="posicaoMenu">
            <h2>Menu</h2>

            <!--<button class="accordion menuTamanho">Cadastro</button>
            <div class="panel menuTamanho sub-menu">
                <p class="menuTamanho">Html.ActionLink("Cadastro Empresa", "Index", "Empresa")</p>
                <p class="menuTamanho">Html.ActionLink("Cadastro Usuário", "Index", "Usuario")</p>
                <p class="menuTamanho">Html.ActionLink("Cadastro Tipo de Servico", "Index", "TipoServico")</p>
            </div>
                -->
            <button class="accordion menuTamanho w3-container">Transação</button>
            <div class="panel menuTamanho sub-menu">
                <p class="menuTamanho">@Html.ActionLink("Enviar Transação", "Index", "Transacao")</p>
                <p class="menuTamanho">@Html.ActionLink("Consultar Transacao", "Consulta", "Transacao")</p>

            </div>

            <button class="accordion menuTamanho w3-container">Analise Transação</button>
            <div class="panel">
                <p class="menuTamanho">@Html.ActionLink("Transações pendentes", "Pendencia", "Transacao")</p>
               <!-- <p class="menuTamanho"  >Html.ActionLink("Lista de Analistas ", "Index", "Transacao")</p>-->
            </div>
        </div>
        <!--Fim Menu-->
        <!--            <hr />
                    <footer>
                        <p>&copy; Prova TECHVIRTUS</p>
                    </footer>
            -->

    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
    <script src="~/Scripts/menu.js" type="text/javascript"></script>
</body>

</html>

TechVirtusProvaEverton/TechVirtusProvaEverton/Views/Shared/_Cliente.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Prova TECHVIRTUS</title>
    <link rel="icon" href="~/Content/img/logoAba.png">
    <link rel="stylesheet" type="text/css" href="~/Content/css/Principal.css">
    <link rel="stylesheet" type="text/css" href="~/Content/css/menuAcordion.css">
    <link rel="stylesheet" type="text/css" href="~/Content/css/CabecalhoTabelas.css">
    <link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
    <link rel="stylesheet" type="text/css" href="~/Content/css/formularios.css">
    <link rel="stylesheet" type="text/css" href="~/Content/css/validacoes.css">

    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a href="~/Home/Index" style="text-decoration:none;color:dimgrey;"><img src="~/Content/img/logo.png" /></a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Logout", "Logout", "Usuario")</li>
                    <li>@Html.ActionLink("Início", "Index", "Home")</li>
                    <li>@Html.ActionLink("Sobre", "About", "Home")</li>
                    <li>@Html.ActionLink("Contato", "Contact", "Home")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content contaner">
        <div id="conteudo">
            @RenderBody()
        </div>
        <!--Menu-->
        <div id="posicaoMenu">
            <h2>Menu</h2>

            <!--<button class="accordion menuTamanho">Cadastro</button>
            <div class="panel menuTamanho sub-menu">
                <p class="menuTamanho">Html.ActionLink("Cadastro Empresa", "Index", "Empresa")</p>
                <p class="menuTamanho">Html.ActionLink("Cadastro Usuário", "Index", "Usuario")</p>
                <p class="menuTamanho">Html.ActionLink("Cadastro Tipo de Servico", "Index", "TipoServico")</p>
            </div>
                -->
            <button class="accordion menuTamanho w3-container">Transação</button>
            <div class="panel menuTamanho sub-menu">
                <p class="menuTamanho">@Html.ActionLink("Enviar Transação", "Index", "Transacao")</p>
                <p class="menuTamanho">@Html.ActionLink("Consultar Transacao", "Consulta", "Transacao")</p>

            </div>

<!--            <button class="accordion menuTamanho w3-container">Analise Transação</button>
            <div class="panel">
                <p class="menuTamanho">Html.ActionLink("Transações pendentes", "Index", "Transacao")</p>
                <p class="menuTamanho">Html.ActionLink("Lista de Analistas ", "Index", "Transacao")</p>
            </div>
        </div>
    -->
        <!--Fim Menu-->
        <!--            <hr />
                    <footer>
                        <p>&copy; Prova TECHVIRTUS</p>
                    </footer>
            -->

    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
    <script src="~/Scripts/menu.js" type="text/javascript"></script>
</body>

</html>

TechVirtusProvaEverton/TechVirtusProvaEverton/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Prova TECHVIRTUS</title>
    <link rel="icon" href="~/Content/img/logoAba.png">
    <link rel="stylesheet" type="text/css" href="~/Content/css/Principal.css">
    <link rel="stylesheet" type="text/css" href="~/Content/css/menuAcordion.css">
    <link rel="stylesheet" type="text/css" href="~/Content/css/CabecalhoTabelas.css">
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a href="~/Home/Index" style="text-decoration:none;color:dimgrey;"><img src="~/Content/img/logo.png" /></a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                                        
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; Prova TECHVIRTUS</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
    <script src="~/Scripts/menu.js" type="text/javascript"></script>
</body>

</html>

TechVirtusProvaEverton/TechVirtusProvaEverton/Views/Shared/_Lembrete.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Prova TECHVIRTUS</title>
    <link rel="icon" href="~/Content/img/logoAba.png">
    <link rel="stylesheet" type="text/css" href="~/Content/css/Principal.css">
    <link rel="stylesheet" type="text/css" href="~/Content/css/menuAcordion.css">
    <link rel="stylesheet" type="text/css" href="~/Content/css/CabecalhoTabelas.css">
    <link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a href="~/Home/Index" style="text-decoration:none;color:dimgrey;"><img src="~/Content/img/logo.png" /></a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Logar", "Login", "Usuario")</li>                    
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        <div id="conteudo">
            @RenderBody()
        </div>
        
        <hr />
        <footer>
            <p>&copy; Prova TECHVIRTUS</p>
        </footer>

    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
    <script src="~/Scripts/menu.js" type="text/javascript"></script>
</body>

</html>

TechVirtusProvaEverton/TechVirtusProvaEverton/Views/Shared/_Principal.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Prova TECHVIRTUS</title>
    <link rel="icon" href="~/Content/img/logoAba.png">
    <link rel="stylesheet" type="text/css" href="~/Content/css/Principal.css">
    <link rel="stylesheet" type="text/css" href="~/Content/css/menuAcordion.css">
    <link rel="stylesheet" type="text/css" href="~/Content/css/CabecalhoTabelas.css">
    <link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
    <link rel="stylesheet" type="text/css" href="~/Content/css/formularios.css">
    <link rel="stylesheet" type="text/css" href="~/Content/css/validacoes.css">
    
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a href="~/Home/Index" style="text-decoration:none;color:dimgrey;"><img src="~/Content/img/logo.png" /></a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Logout", "Logout", "Usuario")</li>
                    <li>@Html.ActionLink("Início", "Index", "Home")</li>
                    <li>@Html.ActionLink("Sobre", "About", "Home")</li>
                    <li>@Html.ActionLink("Contato", "Contact", "Home")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content contaner">
            <div id="conteudo">
                @RenderBody()
            </div>
            <!--Menu-->
            <div id="posicaoMenu">
                <h2>Menu</h2>

                <button class="accordion menuTamanho">Cadastro</button>
                <div class="panel menuTamanho sub-menu">
                    <p class="menuTamanho">@Html.ActionLink("Cadastro Empresa", "Index", "Empresa")</p>
                    <p class="menuTamanho">@Html.ActionLink("Cadastro Usuário", "Index", "Usuario")</p>
                    <p class="menuTamanho">@Html.ActionLink("Cadastro Tipo de Servico", "Index", "TipoServico")</p>
                </div>

                <button class="accordion menuTamanho w3-container">Transação</button>
                <div class="panel menuTamanho sub-menu">
                    <p class="menuTamanho">@Html.ActionLink("Enviar Transação", "Index", "Transacao")</p>
                    <p class="menuTamanho">@Html.ActionLink("Consultar Transacao", "Consulta", "Transacao")</p>
                    
                </div>

                <button class="accordion menuTamanho w3-container">Analise Transação</button>
                <div class="panel">                    
                    <p class="menuTamanho">@Html.ActionLink("Transações pendentes", "Pendencia", "Transacao")</p>
                    <p class="menuTamanho">@Html.ActionLink("Lista de Analistas ", "Analisar", "Transacao")</p>
                </div>
            </div>
            <!--Fim Menu-->
<!--            <hr />
            <footer>
                <p>&copy; Prova TECHVIRTUS</p>
            </footer>
    -->
        
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
    <script src="~/Scripts/menu.js" type="text/javascript"></script>
</body>

</html>